plugins { id 'com.android.application' }

android {
    namespace 'in.itantra.mobile'
    compileSdk 36
    defaultConfig {
        applicationId 'in.itantra.mobile'
        minSdk 29
        targetSdk 35
        versionCode 2
        versionName '1.0'
        ndk { abiFilters 'arm64-v8a' }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    testOptions { unitTests.returnDefaultValues = true }
    packaging {
        resources.excludes += ['META-INF/versions/9/OSGI-INF/MANIFEST.MF']
        jniLibs.excludes += ['**/x86/**', '**/x86_64/**', '**/armeabi-v7a/**']
    }
}

dependencies {
    implementation files('libs/sherpa-onnx-static-link-onnxruntime-1.13.8.aar')
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.23.2'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.86'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2'
    testImplementation 'org.json:json:20250517'
}
