plugins { id 'com.android.application' }
android {
    namespace 'in.itantra.mobile'
    compileSdk 36
    defaultConfig {
        applicationId 'in.itantra.mobile'
        if (project.hasProperty('acousticTest')) applicationIdSuffix '.acoustictest'
        manifestPlaceholders = [appLabel: project.hasProperty('acousticTest') ? 'LinC Acoustic Test' : 'LinC.']
        minSdk 31
        targetSdk 35
        versionCode 1
        versionName '0.1-demo'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
